### ISSUE TITLE
iDigBio Jenkins job has not run in a while - "Still waiting to schedule task Waiting for next available executor"

### ISSUE THREAD

**Issue by mjcollin** [gimmefreshdata/source-idigbio#2]
At http://archive.effechecka.org/, the last successful job was 4 mo 3 days - #24. Currently:

Last build (#41), 4 days 15 hr ago
Last stable build (#24), 4 mo 3 days ago
Last successful build (#24), 4 mo 3 days ago
Last failed build (#33), 2 mo 0 days ago
Last unsuccessful build (#33), 2 mo 0 days ago
Last completed build (#33), 2 mo 0 days ago

Console output of the most recent job #41:

```
Started by timer
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/gimmefreshdata/source-idigbio # timeout=10
Fetching upstream changes from https://github.com/gimmefreshdata/source-idigbio
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/gimmefreshdata/source-idigbio +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 678d89b7b89f7eae09f81ac86748086f6b65c7da (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 678d89b7b89f7eae09f81ac86748086f6b65c7da
 > git rev-list 678d89b7b89f7eae09f81ac86748086f6b65c7da # timeout=10
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor
```

There are 79 items in the build queue overall.

**Comment by mjcollin** [comment]
The worker node is fine as shown on this page: http://archive.effechecka.org/computer/ so it's not out of disk space. Only 3 executors are allowed though so likely other jobs have failed and things are now backed up.

Looking at job #34 which it the first occurring iDigBio failure, this is the console output:

```
[Pipeline] }
Will try again after 15 sec
[Pipeline] {
[Pipeline] echo
checking status...
[Pipeline] sh
[idigbio] Running shell script
+ curl --silent http://api.effechecka.org:7077/v1/submissions/status/driver-20170306191255-0487
[Pipeline] echo
checking status {
  "action" : "SubmissionStatusResponse",
  "driverState" : "NOT_FOUND",
  "serverSparkVersion" : "2.0.1",
  "submissionId" : "driver-20170306191255-0487",
  "success" : false
}
[Pipeline] }
Will try again after 15 sec
```

So, it looks like this (and at least 2 other jobs) are stuck in a 15s retry loop.

**Comment by mjcollin** [comment]
Root cause looks like the Spark job crashed (or was killed when we cleaned out a bunch of stuff) so there is no job status result making this line in the archives.groovy script in to an infinite loop:

https://github.com/gimmefreshdata/archive-importer/blob/master/archives.groovy#L45

@jhpoelen this loop needs max retries or timeout logic, that's a little too adventurous for me this morning but I'll get to it eventually if this keeps happening.

Fix for today: kill Jenkins jobs until things start working.

**Comment by mjcollin** [comment]
In addition to the infinite retry loop (moved to https://github.com/gimmefreshdata/archive-importer/issues/1), the actual job is failing. Inatralist also fails with the same console output so this is related to Spark running jobs or to the higher-up DWCA generating code:

```
[Pipeline] }
Will try again after 2.6 sec
[Pipeline] {
[Pipeline] echo
checking status...
[Pipeline] sh
[idigbio] Running shell script
+ curl --silent http://api.effechecka.org:7077/v1/submissions/status/driver-20170501191220-0148
[Pipeline] echo
checking status {
  "action" : "SubmissionStatusResponse",
  "driverState" : "FINISHED",
  "message" : "task_id {\n  value: \"driver-20170501191220-0148\"\n}\nstate: TASK_FAILED\nmessage: \"Command exited with status 1\"\nslave_id {\n  value: \"20170130-153209-16777343-5050-2298-S0\"\n}\ntimestamp: 1.493680366564568E9\nsource: SOURCE_EXECUTOR\n11: \".\\235\\241\\243Y\\361KJ\\253\\217\\226^@\\343K\\252\"\n",
  "serverSparkVersion" : "2.0.1",
  "submissionId" : "driver-20170501191220-0148",
  "success" : true
}
[Pipeline] }
[Pipeline] // waitUntil
[Pipeline] sh
[idigbio] Running shell script
+ curl --silent http://api.effechecka.org:7077/v1/submissions/status/driver-20170501191220-0148
[Pipeline] error
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: conversion to parquet failed for submission [driver-20170501191220-0148]
Finished: FAILURE
```

**Comment by jhammock** [comment]
(wild cheering)
